### ISSUE TITLE
map to json

### ISSUE THREAD

**Issue by iamkisly** [spiiin/CadEditor#1]
Друг, со следующим релизом добавь экспорт карты в json.

**Comment by spiiin** [comment]
Закоммитил экспорт карты в json в плагин экспорта. Вот собранный плагин:
https://dl.dropboxusercontent.com/u/852723/cad_editor/PluginExportScreens_json.zip
(добавлена кнопка Export To Json на панели экспорта, по аналогии с экспортом в бинарный формат и экспортом в картинку)
