### ISSUE TITLE
Export TMX error!!

### ISSUE THREAD

**Issue by happysoul** [spiiin/CadEditor#14]
I install the soft with win7 x64, the exe path is D:\game\CadEditor
D:\game\nes\DARKWING.NES 
D:\game\CadEditor\settings_nes\darkwing_duck\Settings_DarkwingDuck-All.cs

when i used the export tmx
it's got exception!! 

I know that Chinese is not good for debug, but the useful message is show here ↓
I update .net  framework from 4.6.2 to 4.7.1
and i don‘t know is it a bug? 

--------------------------------------
有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.IO.FileNotFoundException: 未能加载文件或程序集“Microsoft.Scripting, Version=1.1.2.22, Culture=neutral, PublicKeyToken=7f709c5b713576e1”或它的某一个依赖项。系统找不到指定的文件。
文件名:“Microsoft.Scripting, Version=1.1.2.22, Culture=neutral, PublicKeyToken=7f709c5b713576e1”
   在 PluginExportScreens.ExportTMX.btExport_Click(Object sender, EventArgs e)
   在 System.Windows.Forms.Control.OnClick(EventArgs e)
   在 System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   在 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.ButtonBase.WndProc(Message& m)
   在 System.Windows.Forms.Button.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

-------------------------------------

**Comment by spiiin** [comment]
The exception says that CadEditor.exe can't load assembly Microsoft.Scripting. Looks like I forgot to include some files to release archive (I have it somewhere in my local machine, so export works fine for me even without dlls in CadEditor folder) =\

I'll fix it in next release.

It's standart IronPython assemblies:
[CadEditor_IronPythonModules.zip](https://github.com/spiiin/CadEditor/files/2510211/CadEditor_IronPythonModules.zip)

You need to extract it to CadEditor folder (and don't forget to unblock zip archive after download it - https://blogs.msdn.microsoft.com/delay/p/unblockingdownloadedfile/)

**Comment by happysoul** [comment]
I download the zip file, unzip 3 dll files to CadEditor folder, but ... it show another error(alert form).
Export TMX form -> choose a Layout from select box -> click the button Export -> then error
The alert message is:
-------------------------------------
Error (alert form - title)
No module named _functools (alert form - body)
-------------------------------------
It looks like you forgot another .dll file

**Comment by spiiin** [comment]
Check this file
[IronPython.Modules.zip](https://github.com/spiiin/CadEditor/files/2519825/IronPython.Modules.zip)

Later I'll test editor on the fresh machine, if forgot something again, you can install IronPython 2.7. Thanks for testing.

**Comment by happysoul** [comment]
OMG, it works.
it is not enougth after unzip IronPython.Modules.zip into CadEditor folder
First, i download ironPython from github, but the version is 2.7.9 then i think it will be ok ... but fail
Second, i cp all dll from dir of ironPython, but exception of the version... 
Third, i reinstall ironPython of 2.7.7 then cp dll and **Lib dir** （Importent folder!!） into cadEditor, the exprot tmx  works... 
This is the reason why i don't like learn C#

**Comment by happysoul** [comment]
i uninstall cadeditor and reinstall again. it works ... 
maybe install the full IronPython 2.7.7 is the beast choose

https://github.com/IronLanguages/main/releases/tag/ipy-2.7.7

最后总结：安装 CadEditor 需要 2.7.7的 IronPython 才能使用导出 tmx 功能

**Comment by spiiin** [comment]
I rewrote TMX export on pure C#, so now it does not need IronPython or any python library at all.
https://github.com/spiiin/CadEditor/releases/tag/v5.2
