### ISSUE TITLE
[nes] final mission config

### ISSUE THREAD

**Issue by g0me3** [spiiin/CadEditor#23]
"ссылка на объект не указывает на экземпляр объекта"
угораздило меня выбрать именно этот конфиг. или дело не в нем лол?
я думал я обосрался где-то во время редактирования. нет, оригинальный конфиг также

**Comment by spiiin** [comment]
Да вроде всё работает.
![fina_mission](https://user-images.githubusercontent.com/1622049/52958219-abb61200-33a4-11e9-97f3-53f28d7286f0.png)

![fm](https://user-images.githubusercontent.com/1622049/52958256-c092a580-33a4-11e9-891c-457a847aa104.png)

Сверь версию ROM, может не в японской другие смещения.
Для всех игр, имена ROM-ов, на которых проверял (из GoodNES):
https://github.com/spiiin/CadEditor/blob/master/CadEditor/ROMS/copySupportedRomsFromGoodROM.py

**Comment by spiiin** [comment]
Ох, посмотрел на конфиг final mission, он не в той ячейке в таблице.
Там формат блоков такой (блок1тайл1, блок1тайл2, блок1тайл3, блок1тайл4, блок1атрибут, блок2тайл1, блок2тайл2, блок2тайл3, блок2тайл4, блок2атрибут, блок3тайл1,...).
Так что это не совсем твоему формату соответствует. Возьми Капитана Америку.
Закоммитил упрощённый вариант:
https://github.com/spiiin/CadEditor/blob/development/CadEditor/settings_nes/captain_america/Settings_CaptainAmerica-1.cs
Там заодно и показано, как задать несколько наборов экранов:
```
public class Data 
{ 
  public OffsetRec[] getScreensOffsetsForLevels() {
    var ans = new OffsetRec[] {
      new OffsetRec(0x2010, 7 , 16*15, 16, 15),  //1 набор
      new OffsetRec(0x4970, 1 , 16*15, 16, 15), // 2 набор, можно убрать, строку, если других наборов нет
    };
    return ans;  
  }
```
(но проверь, пожалуйста, всё равно, нормально ли final mission японская версия у тебя открывается)

**Comment by spiiin** [comment]
А. В русской версии не узнал ошибку. Это у тебя скорее всего в любой игре будет. Проблема в том, что майкрософт для .net фреймворка, считает все dll, загруженные из интернета "опасными", и их надо разблокировать вручную.

Important: if you download release archive from github, you must unblock it for correct running EXE and DLL files https://blogs.msdn.microsoft.com/delay/p/unblockingdownloadedfile/ More explanations: http://www.romhacking.net/forum/index.php?topic=17150.msg356786#msg356786 You can use installer to avoid this problem.

**Comment by g0me3** [comment]
ни разу в жизи не встречался с такой херней. ни одну программу мне винда втихую не блочила, откуда бы и в каком виде бы я ее не скачивал. без анлока кад едитор на старте вызвал ворнинг винды, чтобы не запускать, но запустил форсом... странная херня.
