### ISSUE TITLE
Cad Editor crashing (?)

### ISSUE THREAD

**Issue by Arcus87** [spiiin/CadEditor#4]
I'm tryed to make a Super Robin Hood hack, but after some time of work in Cad Editor, got crash.

Here's screenshot of crash

![default](https://cloud.githubusercontent.com/assets/21690438/23171477/424e0ea2-f85b-11e6-9ead-649b54ccc301.PNG)

I don't understand crash reason, or it is program or maybe rom brokened

**Comment by Arcus87** [comment]
Video of Cad Editor crashing, i hope it help you.

https://youtu.be/F0dU1P31BqE

**Comment by spiiin** [comment]
Really, it's bug on very big (long or high) maps. Windows Forms controls return negative coordinates if control size > 32768 pixels.
I fixed it (max size of map now 65536 pixels, it's enought for mosst maps) in commit https://github.com/spiiin/CadEditor/commit/3a4c367fbc4b1d6a088987b3f68bc466fec6e897
