### ISSUE TITLE
Contra Force graphics bug

### ISSUE THREAD

**Issue by ghostdogtm** [spiiin/CadEditor#5]
Редактировал первый уровень игры, в редакторе версии 4.2, заметил что некоторые блоки с "битой" графикой и еще не хватает блока под номером 98 на экране B
![contra_force](https://cloud.githubusercontent.com/assets/15708129/25781118/aa3dea4c-333d-11e7-87a2-588062329403.PNG)

**Comment by spiiin** [comment]
Поправил количество блоков.
https://github.com/spiiin/CadEditor/commit/968ac4dddd9387469521637eb05e85d4dcabd8c4

Насчёт блоков с битой графикой - многие игры переключают текущий банк графики, используемый для построения блоков, в коде уровня. Чтобы корректно отобразить их, необходимо описать все дампы памяти в конфиге и переключать их с помощью переключателя Advanced -> VideoBlock
![contra_force_ppu2](https://cloud.githubusercontent.com/assets/1622049/25782602/cb903b1e-3356-11e7-8ff9-27ff5b6dbe58.png)
