### ISSUE TITLE
Broken 1 level archive (Contra Hard Corps)

### ISSUE THREAD

**Issue by ghostdogtm** [spiiin/CadEditor#6]
На стриме у Segaman-a увидели что архив первого лвл-а чуть битый в начале, не то что бы битый, но изменен немного. За остальные не знаю, редактировали только первый уровень.
![default](https://user-images.githubusercontent.com/15708129/31584193-1d29a684-b1b2-11e7-94a8-95e4ff96f5d3.PNG)

**Comment by spiiin** [comment]
Да, это только первый уровень был изменён. Я уже поправил в релизе 4.5 это, спасибо.
